FROM python:3.11-slim

WORKDIR /app

# 安裝依賴
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 複製應用程式碼
COPY world_app.py app.py

# 設置環境變數
ENV HELLO_SERVICE_URL="http://hello-service:5000/"

# 容器啟動命令
CMD ["python", "app.py"]
